2019-11-29 00:18:06,228 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:43]
2019-11-29 00:21:41,259 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:43]
2019-11-29 00:21:50,963 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:43]
2019-11-29 00:26:07,194 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:43]
2019-11-29 00:36:08,395 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:43]
2019-11-29 00:46:04,482 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:45]
2019-11-29 00:53:08,290 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:47]
2019-11-29 00:58:09,884 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:49]
2019-11-29 10:54:29,559 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:49]
2019-11-29 10:56:17,838 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:49]
2019-11-29 10:56:19,729 ERROR: Exception on / [GET] [in c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 22, in index
    posts = current_user.followed_posts().paginate(
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'followed_posts'
2019-11-29 10:56:24,985 ERROR: Exception on /index [GET] [in c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 22, in index
    posts = current_user.followed_posts().paginate(
  File "c:\users\dylmp\scoop\apps\python\3.8.0\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'followed_posts'
2019-11-29 11:05:03,276 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:49]
2019-11-29 11:10:22,049 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:49]
2019-11-29 11:13:15,239 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-11-29 11:47:08,118 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-11-29 11:47:19,151 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-02 18:33:42,368 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:03:38,180 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:03:55,656 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:05:07,413 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:06:57,313 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:08:19,297 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:12:57,541 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:13:40,277 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:13:46,089 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 181, in search
    return render_template('search.html')
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\search.html", line 1, in <module>
    {% extends 'base.html' %}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\search.html", line 14, in root
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 14, in root
    <div class="container">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 93, in block_content
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\search.html", line 25, in block_app_content
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'flask.ctx._AppCtxGlobals object' has no attribute 'search_form'
2019-12-03 21:14:40,219 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:23:04,510 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:23:24,718 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-03 21:24:13,027 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
