2019-12-06 19:21:37,848 ERROR: Exception on /favicon.ico [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\werkzeug\routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1743, in handle_http_exception
    return handler(e)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\404.html", line 1, in <module>
    {% extends "base.html" %}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\404.html", line 14, in root
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 21, in root
    <span class="icon-bar"></span>
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 64, in block_navbar
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-12-06 19:36:21,062 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:50]
2019-12-06 19:36:24,074 ERROR: Exception on /login [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\login.html", line 2, in <module>
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\login.html", line 17, in root
    {% endblock %}
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 21, in root
    <span class="icon-bar"></span>
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 64, in block_navbar
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'search' is undefined
