2019-12-10 12:56:58,647 ERROR: Exception on / [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 29, in index
    return render_template('index.html', title='Home', form=form,
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\index.html", line 2, in <module>
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\index.html", line 17, in root
    <a href="{{ prev_url or '#' }}">
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 14, in root
    <div class="container">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 90, in block_body
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\templates\base.html", line 60, in block_navbar
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.search'. Did you mean 'search' instead?
2019-12-10 13:00:25,379 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:55]
2019-12-10 13:00:36,681 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 187, in search
    current_app.config['POSTS_PER_PAGE'])
NameError: name 'current_app' is not defined
2019-12-10 13:05:05,354 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:55]
2019-12-10 13:05:15,327 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 192, in search
    return render_template('search.html', title=_('Search'), posts=posts,
NameError: name '_' is not defined
2019-12-10 13:05:47,112 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:55]
2019-12-10 13:08:08,670 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:55]
2019-12-10 13:08:17,562 ERROR: Exception on /search [GET] [in C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dylmp\scoop\apps\python\current\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\routes.py", line 186, in search
    posts, total = Post.search(g.search_form.q.data, page,
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\models.py", line 80, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "C:\Users\dylmp\CodeProjects\exampleblog\app\search.py", line 17, in query_index
    if not app.elasticsearch:
AttributeError: module 'flask.app' has no attribute 'elasticsearch'
2019-12-10 13:08:57,286 INFO: Microblog startup [in C:\Users\dylmp\CodeProjects\exampleblog\app\__init__.py:55]
